const navbarItem = [
  {
    src: "/icons/redo.svg",
    alt: "return tool image",
    width: 30,
    height: 30,
    name: "領取刀具",
    path: "/tool-manager/receive-tool",
  },
  {
    src: "/icons/undo.svg",
    alt: "receive tool image",
    width: 30,
    height: 30,
    name: "歸還刀具",
    path: "/tool-manager/return-tool",
  },
  {
    src: "/icons/repair.svg",
    alt: "repair svg ",
    width: 30,
    height: 30,
    name: "修整/報廢",
    path: "/tool-manager/repair-and-scrap",
  },
  {
    src: "/icons/tool.svg",
    alt: "tool svg",
    width: 30,
    height: 30,
    name: "刀具資訊",
    path: "/tool-manager/tool-info",
  },
  {
    src: "/icons/machine.svg",
    alt: "machine svg",
    width: 30,
    height: 30,
    name: "設備資訊",
    path: "/tool-manager/machine-info",
  },
  {
    src: "/icons/label.svg",
    alt: "label svg",
    width: 30,
    height: 30,
    name: "電子標籤資訊",
    path: "/tool-manager/elabel-info",
  },
  {
    src: "/icons/user.svg",
    alt: "user info image",
    width: 30,
    height: 30,
    name: "使用者資訊",
    path: "/tool-manager/user-info",
  },
  {
    src: "/icons/setting.svg",
    alt: "notification icon",
    width: 30,
    height: 30,
    name: "通知設定",
    path: "/tool-manager/setting",
  },
];

export default navbarItem;
