const navbarItem = [
  {
    src: "/returnTool.png",
    alt: "return tool image",
    width: 30,
    height: 30,
    name: "領取刀具",
    path: "/tool-manager/receive-tool",
  },
  {
    src: "/receiveTool.png",
    alt: "receive tool image",
    width: 30,
    height: 30,
    name: "歸還刀具",
    path: "/tool-manager/return-tool",
  },
  {
    src: "/repairAndScrap.png",
    alt: "repair and scrap tool image",
    width: 30,
    height: 30,
    name: "修整/報廢",
    path: "/tool-manager/repair-and-scrap",
  },
  {
    src: "/toolInfo.png",
    alt: "tool info image",
    width: 30,
    height: 30,
    name: "刀具資訊",
    path: "/tool-manager/tool-info",
  },
  {
    src: "/machineInfo.png",
    alt: "machine info image",
    width: 30,
    height: 30,
    name: "設備資訊",
    path: "/tool-manager/machine-info",
  },
  {
    src: "/eLabelInfo.png",
    alt: "eLabel info image",
    width: 30,
    height: 30,
    name: "電子標籤資訊",
    path: "/tool-manager/elabel-info",
  },
  {
    src: "/userInfo.png",
    alt: "user info image",
    width: 30,
    height: 30,
    name: "使用者資訊",
    path: "/tool-manager/user-info",
  },
  {
    src: "/notification.svg",
    alt: "notification icon",
    width: 30,
    height: 30,
    name: "通知設定",
    path: "/tool-manager/setting",
  },
];

export default navbarItem;
